#!/bin/bash

set -o errexit

readonly JOBBER_SCRIPT_DIR=$VOLUMERIZE_HOME
readonly configfile="$(echo ~)/.jobber"


if [[ "$JOBBER_DISABLE" == true ]]; then
  if [ ! -f "${configfile}" ]; then
    # create empty jobber config
    cat > "${configfile}" <<EOF
# This is an empty jobber config file. Jobber has been disabled.
EOF
  else
    echo "Jobber was configured to be disabled, but cannot be disabled because there already is a config file at '$(echo ~)/.jobber'. Please delete/unmount to disable jobber"
  fi

elif [[ -n "$JOBBER_CUSTOM" ]]; then

  returnCode=0
  # Copy the file at location CUSTOM_JOBBER to the root jobs
  cp $JOBBER_CUSTOM $configfile || returnCode=$?

  if [ ${returnCode} -gt 0 ]; then
    echo "failed to copy $CUSTOM_JOBBER to $configfile. Make sure this is not a problem!"
  fi

else
  # Create a jobber file dynamically

  source $CUR_DIR/base.sh

  JOBBER_SCHEDULE=${VOLUMERIZE_JOBBER_TIME:-'0 0 4 * * * *'}
  stdout_sink=$'\n'"      - *stdoutSink"

  job_count=${JOB_COUNT:-1}
  counter=

  for (( counter=1; counter<=$job_count; counter++ ))
  do
    # only set job id if there is more than one job
    job_id=
    if [ $job_count -gt 1 ]; then
      job_id=${counter}
    fi

    job_time="VOLUMERIZE_JOBBER_TIME${job_id}"

    declare "JOB_NAME${counter}"="VolumerizeBackupJob${job_id}"
    declare "JOB_COMMAND${counter}"="${JOBBER_SCRIPT_DIR}/periodicBackup ${job_id}"
    declare "JOB_TIME${counter}"="${!job_time:-${JOBBER_SCHEDULE}}"
  done


  if [ ! -f "${configfile}" ]; then
    touch ${configfile}

    cat >> ${configfile} <<EOF
# Supercronic config file generated by Volumerize

EOF
    for (( i = 1; ; i++ ))
    do
      VAR_JOB_NAME="JOB_NAME$i"
      VAR_JOB_COMMAND="JOB_COMMAND$i"
      VAR_JOB_TIME="JOB_TIME$i"

      if [ ! -n "${!VAR_JOB_NAME}" ]; then
        break
      fi

      it_job_name=${!VAR_JOB_NAME}
      it_job_time=${!VAR_JOB_TIME}
      it_job_command=${!VAR_JOB_COMMAND}

      cat >> ${configfile} <<EOF
# ${it_job_name}
${it_job_time} ${it_job_command}

EOF
    done
  fi
fi

if [ -f ${configfile} ]; then
  cat ${configfile}
fi
