name: Docker Publish

on:
  push:
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
  pull_request_target:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the container to be published"
        required: true
        type: string
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request_target.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Pass tag-suffix as a list, write a custom action that:
  #  * Uses last entry in list to determine context
  #  * computes all permutations of the list
  #  * takes cartesian product of docker generated tags with suffixes
  build-base:
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: default
      version: ${{ inputs.version }}
  build-mongodb:
    needs: [build-base]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: mongodb
      base-image: ${{ needs.build-base.outputs.image }}
      version: ${{ inputs.version }}
  build-mysql:
    needs: [build-base]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: mysql
      base-image: ${{ needs.build-base.outputs.image }}
      version: ${{ inputs.version }}
  build-postgres:
    needs: [build-base]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: postgres
      base-image: ${{ needs.build-base.outputs.image }}
      version: ${{ inputs.version }}
  build-mongodb-mysql:
    needs: [build-mongodb]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: mongodb,mysql
      base-image: ${{ needs.build-mongodb.outputs.image }}
      version: ${{ inputs.version }}
  build-mongodb-postgres:
    needs: [build-mongodb]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: mongodb,postgres
      base-image: ${{ needs.build-mongodb.outputs.image }}
      version: ${{ inputs.version }}
  build-mysql-postgres:
    needs: [build-mysql]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: mysql,postgres
      base-image: ${{ needs.build-mysql.outputs.image }}
      version: ${{ inputs.version }}
  build-mongodb-mysql-postgres:
    needs: [build-mongodb-mysql]
    uses: ./.github/workflows/docker-build.yml
    with:
      strategies: mongodb,mysql,postgres
      base-image: ${{ needs.build-mongodb-mysql.outputs.image }}
      version: ${{ inputs.version }}

  test-base:
    needs: build-base
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-base.outputs.image }}
  test-mongodb:
    needs: build-mongodb
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-mongodb.outputs.image }}
  test-mysql:
    needs: build-mysql
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-mysql.outputs.image }}
  test-postgres:
    needs: build-postgres
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-postgres.outputs.image }}
  test-mongodb-mysql:
    needs: build-mongodb-mysql
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-mongodb-mysql.outputs.image }}
  test-mongodb-postgres:
    needs: build-mongodb-postgres
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-mongodb-postgres.outputs.image }}
  test-mysql-postgres:
    needs: build-mysql-postgres
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-mysql-postgres.outputs.image }}
  test-mongodb-mysql-postgres:
    needs: build-mongodb-mysql-postgres
    uses: ./.github/workflows/docker-test-jobs.yml
    with:
      image-name: ${{ needs.build-mongodb-mysql-postgres.outputs.image }}
